### ISSUE TITLE
Arduino IDE compiling issues 

### ISSUE THREAD

**Issue by kindmartin** [khoih-prog/Blynk_Async_ESP32_BT_WF#1]
Hi, Im loooking to compile the initial examples to run both BLE and Wifi Blynks on a ESP32 but I got this error>

In file included from E:\ProyectosDevs\ArduinoIDE\BLE test\ESP32_BLE\Async_ESP32_BLE_WF\Async_ESP32_BLE_WF.ino:34:0:
defines.h:54:43: fatal error: BlynkSimpleEsp32_Async_BLE_WF.h: No such file or directory
compilation terminated.
exit status 1
BlynkSimpleEsp32_Async_BLE_WF.h: No such file or directory

**Comment by khoih-prog** [comment]
You didn't install the either the Arduino IDE or library correctly and **only you** can do some research and check to know what's wrong.
This has nothing to do with the library as you can reach the so-called `missing` file [**BlynkSimpleEsp32_Async_BLE_WF**](https://github.com/khoih-prog/Blynk_Async_ESP32_BT_WF/blob/master/src/BlynkSimpleEsp32_Async_BLE_WF.h)

The recent compile result is still OK

![image](https://user-images.githubusercontent.com/57012152/108757254-98039000-7517-11eb-83d1-264633335b61.png)
