### ISSUE TITLE
Handle BLE disconnects

### ISSUE THREAD

**Issue by Valeria** [khoih-prog/Blynk_Async_ESP32_BT_WF#2]
Hello, thanks for this wonderful project.

I'm having an issue: If I disconnect BLE connection manually, I can't reconnect to the device until I manually reset it.

Is there a way to handle disconnects so that after one the device starts advertising again? Or even better, a way to check in loop() if there's a disconnect and start advertising?

I fixed it by changing:
```C++
void BlynkTransportEsp32_BLE::onDisconnect(BLEServer* pServer) {
  BLYNK_LOG1(BLYNK_F("BLEDisCon"));
  Blynk_BLE.disconnect();
  disconnect();
      // Start advertising
      pServer->getAdvertising()->start();
}
```

But there's most definitely a better way.
Thank you.

**Comment by khoih-prog** [comment]
The new release has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/Blynk_Async_ESP32_BT_WF#contributions-and-thanks)

---

### Releases v1.2.1

1. Add auto-reconnect feature for BLE. Check [**Handle BLE disconnects** #2](https://github.com/khoih-prog/Blynk_Async_ESP32_BT_WF/issues/2)

**Comment by khoih-prog** [comment]
The new release of the twin library [**BlynkESP32_BT_WF**](https://github.com/khoih-prog/BlynkESP32_BT_WF) has just been published. Your contribution is also noted in [**Contributions and Thanks**](https://github.com/khoih-prog/BlynkESP32_BT_WF#contributions-and-thanks)

---

### Releases v1.2.1

1. Add auto-reconnect feature for BLE. Check [**Handle BLE disconnects** #2](https://github.com/khoih-prog/Blynk_Async_ESP32_BT_WF/issues/2)
